export interface filesModel {
    codigo: string;
    id_persona: number;
    beneficiario: string;
    provincia: string;
    canton: string;
    distrito:string;
    otras_senas: string;
    barrio: string;
    identificacion: string;
    estado: string;
    fecha_creacion: Date;
    fecha_emitido: Date;
    fecha_enviado_entidad: Date;
    ubicacion: string;
    etiqueta: string;
    entidad: string;
    observaciones: string;
    remitente: string;
    asignadoa: string;
    tipo_expediente: string;
    numero_bono: string,
    proposito_bono: string,
    monto_bono: number,
    contrato_CFIA: string,
    acta_traslado: string,
    fecha_envio_acta: Date,
    estado_emitido: string,
    fecha_aprobado: Date,
    folio_real: string,
    numero_plano: string,
    area_construccion: number; // DECIMAL(18,2) en SQL -> number en TypeScript
    ingeniero_responsable: string;
    fiscal: string;
    monto_compra_venta: number;
    monto_presupuesto: number;
    monto_solucion: number;
    monto_comision: number;
    monto_costo_terreno: number;
    monto_honorarios_abogado: number;
    monto_patrimonio_familiar: number;
    monto_poliza: number;
    monto_fiscalizacion: number;
    monto_kilometraje: number;
    monto_afiliacion: number;
    monto_trabajo_social: number;
    monto_construccion: number;
    constructora_asignada: string;
    boleta: string;
    acuerdo_aprobacion: string;
    monto_estudio_social: number;
    monto_aporte_familia: number;
    patrimonio_familiar: string;
    monto_gastos_formalizacion: number;
    monto_aporte_gastos: number;
    monto_diferencia_aporte: number;
    monto_prima_seguros: number;
    usuario_sistema: string;

    situacion_empresa: string;
    expediente: string;
    nuevo_bono: string;
    responsable: string;
    estado_entidad: string;
    codigo_apc: string;
    exoneracion_ley_9635: string;
    profesional: string;
    contrato_empresa: string;
    programa_empresa: string;
    estado_banhvi: string;
    proposito_banhvi: string;
    contacto: string;
    observaciones_ente: string;
    analista_constructora: string;
    analista_ente: string;
    inscrito_hacienda: string;
    fecha_sello_cfia: Date;
    fecha_entrega: Date;
    fecha_devuelto: Date;
    fecha_entrega_recuperado: Date;
    fecha_reingreso: Date;
    fecha_299: Date;
    fecha_enviado_banhvi: Date;
    fecha_carta_agua_recibida: Date;
    fecha_entrega_declaratoria: Date;
    fecha_ingreso_cfia: Date;
    fecha_salida_cfia: Date;
    fecha_entregado_para_enviar: Date;
    fecha_envio_docs_beneficiario: Date;
    fecha_llegada_oficina: Date;
    fecha_permiso_ente: Date;
    fecha_formalizacion: Date;
    fecha_pago_aporte: Date;
    fecha_enviado_construir: Date;
    fecha_pago_avaluo: Date;
    fecha_pago_formalizacion: Date;
    fecha_pago_ts: Date;
    monto_pago_avaluo: number;
    monto_aporte: number;
    monto_pago_formalizacion: number;
    monto_pago_trabajo_social: number;
    comprobante_trabrajo_social: string;
    comprobante_pago_avaluo: string;
    comprobante_pago_formalizacion: string;
    comprobante_aporte: string;
    dias_emitido: number;
    dias_desde_entrega: number;
}